<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-11-03 08:28

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.8 on 2021-11-01 09:51

from django.db import migrations, models
>>>>>>> origin/nena-backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.IntegerField()),
                ('seller_fname', models.CharField(max_length=50)),
                ('seller_lname', models.CharField(max_length=50)),
                ('delivery_type', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField()),
                ('farm_address', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=15)),
                ('loc_long', models.FloatField()),
                ('loc_lat', models.FloatField()),
                ('bldg_cap', models.IntegerField()),
                ('num_pens', models.IntegerField()),
                ('directly_manage', models.BooleanField(default=False)),
                ('total_pigs', models.IntegerField()),
                ('isolation_pen', models.BooleanField(default=False)),
                ('roof_height', models.FloatField()),
                ('feed_trough', models.BooleanField(default=False)),
                ('bldg_curtain', models.BooleanField(default=False)),
                ('medic_tank', models.IntegerField()),
                ('waste_mgt_septic', models.BooleanField(default=False)),
                ('waste_mgt_biogas', models.BooleanField(default=False)),
                ('waste_mgt_others', models.BooleanField(default=False)),
                ('warehouse_length', models.FloatField()),
                ('warehouse_width', models.FloatField()),
                ('road_access', models.BooleanField(default=False)),
                ('extbio_ID', models.IntegerField()),
                ('intbio_ID', models.IntegerField()),
                ('est_time_complete', models.DateField()),
                ('weight_record_ID', models.IntegerField()),
                ('symptoms_record_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pigpen_Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('num_heads', models.IntegerField()),
                ('farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Hog_Raiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip_desc', models.CharField(max_length=500)),
                ('time_departure', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('delivery_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.delivery')),
                ('farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm')),
=======
            name='ExternalBiosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_proof', models.IntegerField()),
                ('perim_fence', models.IntegerField()),
                ('fiveh_m_dist', models.IntegerField()),
                ('prvdd_foot_dip', models.IntegerField()),
                ('prvdd_alco_soap', models.IntegerField()),
                ('obs_no_visitors', models.IntegerField()),
                ('prsnl_dip_footwear', models.IntegerField()),
                ('prsnl_sanit_hands', models.IntegerField()),
                ('chg_disinfect_daily', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalBiosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isol_pen', models.IntegerField()),
                ('waste_mgt', models.IntegerField()),
                ('foot_dip', models.IntegerField()),
                ('disinfect_prem', models.IntegerField()),
                ('disinfect_vet_supp', models.IntegerField()),
>>>>>>> origin/nena-backend
            ],
        ),
    ]
