# Generated by Django 3.2.8 on 2021-11-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBiosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_proof', models.IntegerField()),
                ('perim_fence', models.IntegerField()),
                ('fiveh_m_dist', models.IntegerField()),
                ('prvdd_foot_dip', models.IntegerField()),
                ('prvdd_alco_soap', models.IntegerField()),
                ('obs_no_visitors', models.IntegerField()),
                ('prsnl_dip_footwear', models.IntegerField()),
                ('prsnl_sanit_hands', models.IntegerField()),
                ('chg_disinfect_daily', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalBiosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isol_pen', models.IntegerField()),
                ('waste_mgt', models.IntegerField()),
                ('foot_dip', models.IntegerField()),
                ('disinfect_prem', models.IntegerField()),
                ('disinfect_vet_supp', models.IntegerField()),
            ],
        ),
    ]
