# Generated by Django 3.2.8 on 2021-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='feed_through',
        ),
        migrations.AddField(
            model_name='farm',
            name='feed_trough',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='bldg_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='bldg_curtain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='date_filed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='directly_manage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='isolation_pen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='medic_tank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='num_headsApplied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='num_pens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='raiser_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='raiser_uname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='road_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='roof_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_pigs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='warehouse_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='warehouse_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='waste_mgt_biogas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='waste_mgt_others',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='waste_mgt_septic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
