# Generated by Django 3.2.8 on 2021-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hog_symptoms',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='activities_form',
            name='is_checked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='activities_form',
            name='is_noted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='activities_form',
            name='is_reported',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
