# Generated by Django 3.2.8 on 2021-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='feed_trough',
            field=models.CharField(choices=[('Semi-automatic', 'Semi-automatic'), ('Trough', 'Trough')], default='Semi-automatic', max_length=15),
        ),
    ]
