# Generated by Django 3.2.8 on 2021-11-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='external_bio_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='internal_bio_ID',
            field=models.IntegerField(null=True),
        ),
    ]
