# Generated by Django 3.2.8 on 2021-11-02 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbiosec',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='internalbiosec',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
