# Generated by Django 3.2.8 on 2021-11-07 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='raiser_ID',
            field=models.IntegerField(null=True),
        ),
    ]
