# Generated by Django 3.2.8 on 2021-11-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0002_alter_farm_feed_trough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='extbio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.externalbiosec'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_symptoms',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm_symptoms'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_weight',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm_weight'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.internalbiosec'),
        ),
    ]
