# Generated by Django 3.2.8 on 2021-11-02 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0002_auto_20211102_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbiosec',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='internalbiosec',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
