# Generated by Django 3.2.8 on 2021-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0002_auto_20211216_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='hog_symptoms',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
