# Generated by Django 3.2.8 on 2021-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0002_auto_20211102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='activity_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='est_time_complete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='external_bio_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='internal_bio_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='symptoms_record_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='weight_record_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
