# Generated by Django 3.2.8 on 2021-11-07 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0002_auto_20211107_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='area',
            field=models.CharField(choices=[('TISISI', 'TISISI'), ('West', 'West'), ('East', 'East'), ('Other', 'Other')], default='TISISI', max_length=15),
        ),
        migrations.AlterField(
            model_name='farm',
            name='bldg_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='date_registered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='est_time_complete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='extbio_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='loc_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='loc_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='medic_tank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='num_pens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='raiser_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='roof_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='symptoms_record_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_pigs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='warehouse_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='warehouse_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='weight_record_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
