# Generated by Django 3.2.8 on 2021-11-08 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0003_auto_20211108_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_symptoms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
