# Generated by Django 3.2.8 on 2021-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0003_auto_20211107_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigpen_measures',
            name='farm_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
