# Generated by Django 3.2.8 on 2021-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0003_auto_20211102_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('raiser_ID', models.IntegerField()),
                ('trip_description', models.CharField(max_length=500)),
                ('time_departure', models.DateTimeField()),
                ('time_arrival', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('technician_ID', models.IntegerField()),
            ],
        ),
    ]
