# Generated by Django 3.2.8 on 2021-12-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0003_hog_symptoms_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortality_form',
            name='ref_mortality',
        ),
        migrations.AddField(
            model_name='mortality',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mortality',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mortality',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mortality',
            name='mortality_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.mortality_form'),
        ),
        migrations.AddField(
            model_name='mortality_form',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
