# Generated by Django 3.2.8 on 2021-11-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0004_auto_20211102_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm_Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField()),
                ('high_fever', models.BooleanField(default=False)),
                ('loss_appetite', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('lethargic', models.BooleanField(default=False)),
                ('constipation', models.BooleanField(default=False)),
                ('vomit_diarrhea', models.BooleanField(default=False)),
                ('colored_pigs', models.BooleanField(default=False)),
                ('skin_lesions', models.BooleanField(default=False)),
                ('hemorrhages', models.BooleanField(default=False)),
                ('abn_breathing', models.BooleanField(default=False)),
                ('discharge_eyesnose', models.BooleanField(default=False)),
                ('death_isDays', models.BooleanField(default=False)),
                ('death_isWeek', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('sneeze', models.BooleanField(default=False)),
                ('runny_nose', models.BooleanField(default=False)),
                ('waste_mgt', models.BooleanField(default=False)),
                ('boar_dec_libido', models.BooleanField(default=False)),
                ('farrow_miscarriage', models.BooleanField(default=False)),
                ('weight_loss', models.BooleanField(default=False)),
                ('trembling', models.BooleanField(default=False)),
                ('conjunctivitis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_filed', models.DateField()),
                ('is_starter', models.BooleanField(default=False)),
                ('ave_weight', models.FloatField()),
                ('total_numHeads', models.IntegerField()),
                ('total_kls', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='extbio_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.externalbiosec'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.internalbiosec'),
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=15)),
                ('series', models.IntegerField()),
                ('mortality_date', models.DateTimeField()),
                ('num_begInv', models.IntegerField()),
                ('num_today', models.IntegerField()),
                ('num_toDate', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=500)),
                ('farm_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm')),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='symptoms_record_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm_symptoms'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='weight_record_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsapp.farm_weight'),
        ),
    ]
