# Generated by Django 3.2.8 on 2021-12-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0004_auto_20211218_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortality',
            old_name='mortality_date',
            new_name='date',
        ),
    ]
