# Generated by Django 3.2.8 on 2021-11-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0004_auto_20211102_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extbio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.externalbiosec')),
                ('intbio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.internalbiosec')),
            ],
        ),
    ]
