# Generated by Django 3.2.8 on 2021-11-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0004_alter_pigpen_measures_farm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbiosec',
            name='bird_proof',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='chg_disinfect_daily',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='fiveh_m_dist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='obs_no_visitors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='perim_fence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='prsnl_dip_footwear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='prsnl_sanit_hands',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='prvdd_alco_soap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalbiosec',
            name='prvdd_foot_dip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalbiosec',
            name='disinfect_prem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalbiosec',
            name='disinfect_vet_supp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalbiosec',
            name='foot_dip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalbiosec',
            name='isol_pen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internalbiosec',
            name='waste_mgt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
