# Generated by Django 3.2.8 on 2021-11-08 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0005_auto_20211108_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='date_registered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='extbio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.externalbiosec'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='hog_raiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.hog_raiser'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.internalbiosec'),
        ),
    ]
