# Generated by Django 3.2.8 on 2021-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0005_auto_20211103_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='extbio_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio_ID',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ExternalBiosec',
        ),
        migrations.DeleteModel(
            name='InternalBiosec',
        ),
    ]
