# Generated by Django 3.2.8 on 2021-11-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0005_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='extbio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extbio', to='farmsapp.externalbiosec'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intbio', to='farmsapp.internalbiosec'),
        ),
    ]
