# Generated by Django 3.2.8 on 2021-12-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0005_rename_mortality_date_mortality_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortality',
            old_name='date',
            new_name='mortality_date',
        ),
    ]
