# Generated by Django 3.2.8 on 2021-11-03 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0006_auto_20211103_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBiosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bird_proof', models.IntegerField(null=True)),
                ('perim_fence', models.IntegerField(null=True)),
                ('fiveh_m_dist', models.IntegerField(null=True)),
                ('prvdd_foot_dip', models.IntegerField(null=True)),
                ('prvdd_alco_soap', models.IntegerField(null=True)),
                ('obs_no_visitors', models.IntegerField(null=True)),
                ('prsnl_dip_footwear', models.IntegerField(null=True)),
                ('prsnl_sanit_hands', models.IntegerField(null=True)),
                ('chg_disinfect_daily', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalBiosec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('isol_pen', models.IntegerField(null=True)),
                ('waste_mgt', models.IntegerField(null=True)),
                ('foot_dip', models.IntegerField(null=True)),
                ('disinfect_prem', models.IntegerField(null=True)),
                ('disinfect_vet_supp', models.IntegerField(null=True)),
            ],
        ),
    ]
