# Generated by Django 3.2.8 on 2021-11-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0006_auto_20211109_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbiosec',
            name='ref_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.farm'),
        ),
        migrations.AddField(
            model_name='internalbiosec',
            name='ref_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.farm'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='extbio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.externalbiosec'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intbio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmsapp.internalbiosec'),
        ),
    ]
