# Generated by Django 3.2.8 on 2021-12-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0006_rename_date_mortality_mortality_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='mortality_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='ref_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.farm'),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
