# Generated by Django 3.2.8 on 2021-12-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0008_auto_20211219_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
    ]
