# Generated by Django 3.2.8 on 2021-11-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0008_auto_20211111_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memannouncement',
            name='author_ID',
        ),
        migrations.AddField(
            model_name='memannouncement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='farmsapp.user'),
        ),
    ]
