# Generated by Django 3.2.8 on 2021-12-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0010_auto_20211219_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
