# Generated by Django 3.2.8 on 2021-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0011_alter_mortality_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality_form',
            name='is_noted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mortality_form',
            name='is_posted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mortality_form',
            name='is_reported',
            field=models.BooleanField(null=True),
        ),
    ]
