# Generated by Django 3.2.8 on 2021-12-25 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmsapp', '0012_auto_20211219_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='activities_form',
            name='ref_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.farm'),
        ),
        migrations.AddField(
            model_name='mortality_form',
            name='ref_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.farm'),
        ),
        migrations.AlterField(
            model_name='area',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='farmsapp.area'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmsapp.farm_weight'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='hog_raiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmsapp.hog_raiser'),
        ),
        migrations.AlterField(
            model_name='hog_symptoms',
            name='ref_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.farm'),
        ),
        migrations.AlterField(
            model_name='mem_announcement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
