# Generated by Django 3.2.8 on 2021-12-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0013_auto_20211225_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_form',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pigpen_measures',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
