# Generated by Django 3.2.8 on 2021-12-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0015_alter_activities_form_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigpen_measures',
            name='final_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.farm_weight'),
        ),
        migrations.AddField(
            model_name='pigpen_measures',
            name='start_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.farm_weight'),
        ),
    ]
