# Generated by Django 3.2.8 on 2021-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0016_auto_20211227_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities_form',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
