# Generated by Django 3.2.8 on 2021-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0018_auto_20211228_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortality',
            name='series',
        ),
        migrations.AddField(
            model_name='activities_form',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mortality_form',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mortality_form',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
