# Generated by Django 3.2.8 on 2022-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0019_auto_20211229_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='num_begInv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='num_toDate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
