# Generated by Django 3.2.8 on 2022-01-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmsapp', '0021_auto_20220105_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm_weight',
            old_name='is_approved',
            new_name='is_noted',
        ),
        migrations.AddField(
            model_name='farm_weight',
            name='is_posted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='farm_weight',
            name='weight_asm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_asm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm_weight',
            name='weight_mgtStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_mgtStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
