# Generated by Django 3.2.8 on 2022-01-09 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmsapp', '0022_auto_20220107_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_weight',
            name='weight_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_Tech', to=settings.AUTH_USER_MODEL),
        ),
    ]
