# Generated by Django 3.2.8 on 2022-03-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0025_auto_20220120_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortality',
            name='source',
        ),
        migrations.AddField(
            model_name='mortality',
            name='incid_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.hog_symptoms'),
        ),
        migrations.CreateModel(
            name='Hog_Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_weight', models.FloatField()),
                ('farm_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmsapp.farm_weight')),
            ],
        ),
    ]
