# Generated by Django 3.2.8 on 2022-04-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0026_auto_20220322_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.AddField(
            model_name='activity',
            name='num_pigs_inv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mortality',
            name='source',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
