# Generated by Django 3.2.8 on 2022-04-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0027_auto_20220415_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='hog_raiser',
            name='mem_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hog_symptoms',
            name='others',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='hog_symptoms',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Disease_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('lab_result', models.IntegerField()),
                ('lab_ref_no', models.IntegerField()),
                ('date_updated', models.DateTimeField()),
                ('incid_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.hog_symptoms')),
            ],
        ),
    ]
