# Generated by Django 3.2.8 on 2022-04-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0028_auto_20220415_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='num_pigs_inv',
            field=models.IntegerField(default=0),
        ),
    ]
