# Generated by Django 3.2.8 on 2022-04-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0029_auto_20220416_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='num_pigs_inv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease_case',
            name='lab_ref_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease_case',
            name='lab_result',
            field=models.BooleanField(null=True),
        ),
    ]
