# Generated by Django 3.2.8 on 2022-04-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0030_auto_20220416_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_case',
            name='lab_result',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
