# Generated by Django 3.2.8 on 2022-04-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0031_auto_20220416_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortality',
            name='source',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
