# Generated by Django 3.2.8 on 2022-04-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0035_auto_20220418_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortality',
            name='incid_case',
        ),
        migrations.AddField(
            model_name='mortality',
            name='case_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
