# Generated by Django 4.0 on 2022-05-05 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0040_auto_20220501_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEIRD_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50)),
                ('incub_days', models.IntegerField()),
                ('reproduction_num', models.FloatField()),
                ('days_can_spread', models.IntegerField()),
                ('fatality_rate', models.FloatField()),
                ('days_til_death', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='disease_case',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disease_record',
            name='date_filed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
