# Generated by Django 3.2.8 on 2022-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0041_seird_input_alter_disease_case_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=20)),
                ('plan_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SEIRD_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_incub_days', models.IntegerField()),
                ('max_incub_days', models.IntegerField()),
                ('min_reproduction_num', models.FloatField()),
                ('max_reproduction_num', models.FloatField()),
                ('min_days_can_spread', models.IntegerField()),
                ('max_days_can_spread', models.IntegerField()),
                ('min_fatality_rate', models.FloatField()),
                ('max_fatality_rate', models.FloatField()),
                ('min_days_til_death', models.IntegerField()),
                ('max_days_til_death', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Threshold_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
