# Generated by Django 3.2.8 on 2022-05-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0043_seird_range_seird_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold_values',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
