# Generated by Django 3.2.8 on 2022-05-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0044_alter_threshold_values_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seird_range',
            name='seird_input',
        ),
        migrations.AddField(
            model_name='seird_input',
            name='seird_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.seird_range'),
        ),
    ]
