# Generated by Django 4.0 on 2022-06-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmsapp', '0045_auto_20220519_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='hog_symptoms',
            name='prev_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farmsapp.hog_symptoms'),
        ),
    ]
